%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%% MAIN_FRAME SPATIAL TETHYS %%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function[V,O,Vice,Oice,ZWT,OF,OS,OH,OL,Psi_s_H,Psi_s_L,Rd,Qi_out,...
    Rh,Lk,f,WIS,Ts,Csno,Cice,NDVI,...
    Pr_sno,Pr_liq,rb_H,rb_L,rs_sunH,rs_sunL,rs_shdH,rs_shdL,...
    rap_H,rap_L,r_soil,b_soil,alp_soil,ra,r_litter,...
    WR_SP,U_SWE,NIn_SWE,dQ,DQ,DT,...
    WAT,ICE,ICE_D,IP_wc,WR_IP,NIce,Cicew,Csnow,FROCK,...
    Dr_H,Dr_L,SE_rock,SE_urb,Lk_wat,Lk_rock,...
    An_L,An_H,Rdark_L,Rdark_H,Ci_sunH,Ci_sunL,Ci_shdH,Ci_shdL,Rn,...
    H,QE,Qv,Lpho,T_H,T_L,EIn_H,EIn_L,EG,ELitter,ESN,ESN_In,EWAT,EICE,EIn_urb,EIn_rock,dw_SNO,Imelt,Smelt,...
    G,Gfin,Tdp,Tdpsnow,Tdeb,Tice,Tdamp,Tdp_H,Tdp_L,SWE,SND,ros,In_SWE,SP_wc,Qfm,t_sls,...
    In_H,In_L,In_Litter,In_urb,In_rock,...
    gsr_H,Psi_x_H,Psi_l_H,Jsx_H,Jxl_H,Kleaf_H,Kx_H,Vx_H,Vl_H,...
    gsr_L,Psi_x_L,Psi_l_L,Jsx_L,Jxl_L,Kleaf_L,Kx_L,Vx_L,Vl_L,...
    fapar_H,fapar_L,SIF_H,SIF_L,...
    Ws_under,er,snow_albedo,tau_sno,e_sno,HV,QEV,dQVEG,TsV,Ts_under,EK,POT,CK1]=HYDROLOGY_MODULE_PAR(Vtm1,Oicetm1,aR,Zs,...
    EvL_Zs,Inf_Zs,Zinf,RfH_Zs,RfL_Zs,dz,Dz,ms,Kbot,Pr,Ta,Ds,Ws,zatm,Tstm1,dt,dth,ea,N,Pre,Tstm0,...
    LAI_H,SAI_H,LAI_L,SAI_L,LAIdead_H,LAIdead_L,Rrootl_H,Rrootl_L,BLit,Sllit,Kct,...
    Datam,DeltaGMT,Lon,Lat,t_bef,t_aft,...
    Ccrown,Cbare,Crock,Curb,Cwat,...
    SAB1,SAB2,SAD1,SAD2,PARB,PARD,SvF,SNDtm1,snow_albedotm1,Color_Class,OM_H,OM_L,...
    PFT_opt_H,PFT_opt_L,hc_H,hc_L,d_leaf_H,d_leaf_L,...
    Soil_Param,Interc_Param,SnowIce_Param,VegH_Param,VegL_Param,...
    Ca,Oa,Citm1_sunH,Citm1_shdH,Citm1_sunL,Citm1_shdL,...
    e_rel_H,e_relN_H,e_rel_L,e_relN_L,...
    e_snotm1,In_Htm1,In_Ltm1,In_Littertm1,In_urbtm1,In_rocktm1,SWEtm1,In_SWEtm1,....
    Tdebtm1,Ticetm1,Tdptm1,Tdpsnowtm1,Tdamptm1,Tstm1_under,...
    WATtm1,ICEtm1,IP_wctm1,ICE_Dtm1,Cicewtm1,...
    Vx_Htm1,Vl_Htm1,Vx_Ltm1,Vl_Ltm1,Psi_x_Htm1,Psi_l_Htm1,Psi_x_Ltm1,Psi_l_Ltm1,...
    ZR95_H,ZR95_L,...
    FROCKtm1,Krock,...
    Urb_Par,Deb_Par,Zs_deb,...
    Tdew,t_slstm1,rostm1,SP_wctm1,fpr,IrD,...
    In_max_urb,In_max_rock,K_usle,tau_snotm1,Ta_day,Slo_top,Slo_pot,Asur,Ared,aTop,EKtm1,q_runon,Qi_in,...
    Ws_undertm1,Pr_sno_day,...
    pow_dis,a_dis,Salt,...
    SPAR,SN,OPT_min_SPD,OPT_VegSnow,OPT_SoilTemp,OPT_PlantHydr,Opt_CR,Opt_ST,Opt_ST2,OPT_SM,OPT_STh,OPT_FR_SOIL,OPT_PH)
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%% TEMPORARY SOLUTION %%%%%
%Restating_parameters_temporary; 
%%%%%%%%%%%%%%%%%%%%%%%%%%
cc_max=length(LAI_H); %% Max Number of PFTs
cc=length(Ccrown); %% PFTs in this cell
if not(cc==cc_max)
    Citm1_sunL = Citm1_sunL(1:cc);
    Citm1_sunH = Citm1_sunH(1:cc);
    Citm1_shdL = Citm1_shdL(1:cc);
    Citm1_shdH = Citm1_shdH(1:cc);
    In_Htm1 = In_Htm1(1:cc);
    In_Ltm1 = In_Ltm1(1:cc);
    LAI_H =LAI_H(1:cc);
    LAI_L =LAI_L(1:cc);
    SAI_H =SAI_H(1:cc);
    SAI_L =SAI_L(1:cc);
    hc_H =hc_H(1:cc);
    hc_L =hc_L(1:cc);
    e_rel_H =e_rel_H(1:cc);
    e_rel_L =e_rel_L(1:cc);
    e_relN_H =e_relN_H(1:cc);
    e_relN_L =e_relN_L(1:cc);
    LAIdead_H =LAIdead_H(1:cc);
    LAIdead_L =LAIdead_L(1:cc);
    Rrootl_H=Rrootl_H(1:cc);
    Rrootl_L=Rrootl_L(1:cc);
    Vx_Htm1=Vx_Htm1(1:cc);
    Vl_Htm1=Vx_Ltm1(1:cc);
    Vx_Ltm1=Vx_Ltm1(1:cc);
    Vl_Ltm1=Vl_Ltm1(1:cc);
    Psi_x_Htm1=Psi_x_Htm1(1:cc);
    Psi_l_Htm1=Psi_l_Htm1(1:cc);
    Psi_x_Ltm1=Psi_x_Ltm1(1:cc);
    Psi_l_Ltm1=Psi_l_Ltm1(1:cc);
    BLit=BLit(1:cc);
    In_Littertm1= In_Littertm1(1:cc);
end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
snow_albtm1.dir_vis = snow_albedotm1(1);
snow_albtm1.dif_vis = snow_albedotm1(2);
snow_albtm1.dir_nir = snow_albedotm1(3);
snow_albtm1.dif_nir = snow_albedotm1(4);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%
[V,Vice,O,Oice,ZWT,OF,OS,OH,OL,Psi_s_H,Psi_s_L,Rd,Qi_out,WTR,...
    Rh,Lk,f,WIS,Ts,Pr_sno,Pr_liq,Csno,Cice,NDVI,rb_H,rb_L,rs_sunH,...
    rs_sunL,rs_shdH,rs_shdL,r_litter,...
    An_L,An_H,Rdark_L,Rdark_H,Ci_sunH,Ci_sunL,Ci_shdH,Ci_shdL,...
    rap_H,rap_L,r_soil,b_soil,alp_soil,ra,Rn,...
    H,QE,Qv,Lpho,T_H,T_L,EIn_H,EIn_L,EG,ESN,ESN_In,ELitter,EWAT,EICE,EIn_urb,EIn_rock,dw_SNO,...
    G,Gfin,Tdp,Tdpsnow,Tdeb,Tdamp,Tice,Tdp_H,Tdp_L,SWE,SND,ros,In_SWE,SP_wc,WR_SP,U_SWE,NIn_SWE,dQ,Qfm,t_sls,DQ,DT,...
    WAT,ICE,ICE_D,IP_wc,WR_IP,NIce,Cicew,Csnow,FROCK,Imelt,Smelt,...
    In_H,In_L,In_Litter,In_urb,In_rock,Dr_H,Dr_L,SE_rock,SE_urb,Lk_wat,Lk_rock,er,...
    gsr_H,Psi_x_H,Psi_l_H,Jsx_H,Jxl_H,Kleaf_H,Kx_H,Vx_H,Vl_H,...
    gsr_L,Psi_x_L,Psi_l_L,Jsx_L,Jxl_L,Kleaf_L,Kx_L,Vx_L,Vl_L,...
    fapar_H,fapar_L,SIF_H,SIF_L,...
    snow_alb,tau_sno,e_sno,Ws_under,dQVEG,HV,QEV,TsV,Ts_under,EK,POT]=HYDROLOGIC_UNIT(Vtm1,Oicetm1,aR,Zs,...
    EvL_Zs,Inf_Zs,Zinf,RfH_Zs,RfL_Zs,dz,Dz,ms,Kbot,Pr,Ta,Ds,Ws,zatm,Tstm1,Tstm1_under,IrD,dt,dth,ea,N,Pre,Tstm0,...
    LAI_H,SAI_H,LAI_L,SAI_L,LAIdead_H,LAIdead_L,Rrootl_H,Rrootl_L,BLit,Sllit,Kct,...
    Datam,DeltaGMT,Lon,Lat,t_bef,t_aft,...
    Ccrown,Cbare,Crock,Curb,Cwat,...
    Soil_Param,Interc_Param,SnowIce_Param,VegH_Param,VegL_Param,...
    Zs_deb,Deb_Par,...
    ZR95_H,ZR95_L,...
    SAB1,SAB2,SAD1,SAD2,PARB,PARD,SvF,SNDtm1,snow_albtm1,Color_Class,OM_H,OM_L,...
    PFT_opt_H,PFT_opt_L,hc_H,hc_L,d_leaf_H,d_leaf_L,...
    Ca,Oa,Citm1_sunH,Citm1_shdH,Citm1_sunL,Citm1_shdL,...
    e_rel_H,e_relN_H,e_rel_L,e_relN_L,...
    e_snotm1,In_Htm1,In_Ltm1,In_Littertm1,In_urbtm1,In_rocktm1,SWEtm1,In_SWEtm1,....
    Tdebtm1,Tdptm1,Tdpsnowtm1,Tdamptm1,Ticetm1,...
    WATtm1,ICEtm1,IP_wctm1,ICE_Dtm1,Cicewtm1,...
    Vx_Htm1,Vl_Htm1,Vx_Ltm1,Vl_Ltm1,Psi_x_Htm1,Psi_l_Htm1,Psi_x_Ltm1,Psi_l_Ltm1,...
    FROCKtm1,Krock,Ws_undertm1,...
    Tdew,t_slstm1,rostm1,SP_wctm1,fpr,Pr_sno_day,...
    Urb_Par,In_max_urb,In_max_rock,K_usle,tau_snotm1,Ta_day,Slo_top,Slo_pot,Asur,Ared,aTop,EKtm1,q_runon,Qi_in,...
    pow_dis,a_dis,Salt,...
    SPAR,SN,OPT_min_SPD,OPT_VegSnow,OPT_SoilTemp,OPT_PlantHydr,Opt_CR,Opt_ST,Opt_ST2,OPT_SM,OPT_STh,OPT_FR_SOIL,OPT_PH);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
snow_albedo(1)=snow_alb.dir_vis;
snow_albedo(2)=snow_alb.dif_vis;
snow_albedo(3)=snow_alb.dir_nir;
snow_albedo(4)=snow_alb.dif_nir;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
gsr_H = gsr_H';
gsr_L = gsr_L';
%%%%
if not(cc==cc_max)
    OL(cc+1:cc_max) = 0;
    OH(cc+1:cc_max) = 0;
    rb_H(cc+1:cc_max) = 0;
    rb_L(cc+1:cc_max) = 0;
    rs_sunH(cc+1:cc_max) = 0;
    rs_sunL(cc+1:cc_max) = 0;
    rs_shdH(cc+1:cc_max) = 0;
    rs_shdL(cc+1:cc_max) = 0;
    rap_H(cc+1:cc_max) = 0;
    rap_L(cc+1:cc_max) = 0;
    An_H(cc+1:cc_max) = 0;
    An_L(cc+1:cc_max) = 0;
    Rdark_H(cc+1:cc_max) = 0;
    Rdark_L(cc+1:cc_max) = 0;
    Ci_sunH(cc+1:cc_max) = 0;
    Ci_sunL(cc+1:cc_max) = 0;
    Ci_shdH(cc+1:cc_max) = 0;
    Ci_shdL(cc+1:cc_max) = 0;
    T_H(cc+1:cc_max) = 0;
    T_L(cc+1:cc_max) = 0;
    EIn_H(cc+1:cc_max) = 0;
    EIn_L(cc+1:cc_max) = 0;
    In_H(cc+1:cc_max) = 0;
    In_L(cc+1:cc_max) = 0;
    Tdp_H(cc+1:cc_max) = 0;
    Tdp_L(cc+1:cc_max) = 0;
    %r_litter(cc+1:cc_max)=0;
    Psi_s_H(cc+1:cc_max) = 0;
    Psi_s_L(cc+1:cc_max) = 0;
    gsr_H(cc+1:cc_max) = 0;
    Psi_x_H(cc+1:cc_max) = 0;
    Psi_l_H(cc+1:cc_max) = 0;
    Jsx_H(cc+1:cc_max) = 0;
    Jxl_H(cc+1:cc_max) = 0;
    Kleaf_H(cc+1:cc_max) = 0;
    Kx_H(cc+1:cc_max) = 0;
    Vx_H(cc+1:cc_max) = 0;
    Vl_H(cc+1:cc_max) = 0;
    gsr_L(cc+1:cc_max) = 0;
    Psi_x_L(cc+1:cc_max) = 0;
    Psi_l_L(cc+1:cc_max) = 0;
    Jsx_L(cc+1:cc_max) = 0;
    Jxl_L(cc+1:cc_max) = 0;
    Kleaf_L(cc+1:cc_max) = 0;
    Kx_L(cc+1:cc_max) = 0;
    Vx_L(cc+1:cc_max) = 0;
    Vl_L(cc+1:cc_max) = 0;
    fapar_H(cc+1:cc_max) = 0;
    fapar_L(cc+1:cc_max) = 0;
    SIF_H(cc+1:cc_max) = 0;
    SIF_L(cc+1:cc_max) = 0;
end
%%%%
if Crock ==1 || Curb ==1 || Cwat ==1
    CK1=0;
else
    %%% n-coordinate
    CK1 = f*dth + sum(Vtm1 - V) + sum((Oicetm1).*dz - Vice) - EG*dth/(Asur*Ared) - Lk*dth/(Asur*Ared) ...
        - sum(Qi_out)*dth/(Asur*Ared) -Rd/(Asur*Ared) -sum(Jsx_L).*dth/(Asur*Ared) -sum(Jsx_H).*dth/(Asur*Ared)  + sum(Qi_in)*dth/(Asur*Ared) ;

end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
return
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%



