%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%% CLOSURE ENERGY BUDGET  DETERMINATION SURFACE TEMPERATURE %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function[DQ]=Surface_Temperature_2Temp(Ts,dt,Ta,ea,Latm,SvF,Pre,...
    Csno,Crock,Curb,Cbare,Ccrown,Cwat,Cice,...
    hc_H,hc_L,SnoDep,ydepth,ICE_D,Cdeb,LAI_H,LAI_L,SAI_H,SAI_L,...
    RabsbSun_vegH,RabsbShd_vegH,Rabsb_soiH,...
    RabsbSun_vegL,RabsbShd_vegL,Rabsb_soiL,FsunH,FshdH,...
    FsunL,FshdL,Rabsb_sno,Rabsb_bare,Rabsb_urb,Rabsb_wat,Rabsb_rock,Rabsb_ice,Rabsb_deb,...
    e_sno,e_gr,e_sur,Cicew,Csnow,CLitter,...
    dw_L,dw_H,dw_SNO,...
    In_H,In_L,In_urb,In_rock,SWE,In_SWE,...
    Pr_liq,Pr_sno,rs_sunH,rs_sunL,rs_shdH,rs_shdL,d_leaf_H,d_leaf_L,r_litter,r_soil,b_soil,alp_soil,...
    ms,dz,Zs,rsd,lan_dry,lan_s,cv_s,SPAR,L,Pe,O33,alpVG,nVG,Phy,s_SVG,bVG,Osat,Ohy,Oicetm1,Otm1,...
    Tstm1_H,Tstm1_L,Tdamptm1,Tdptm1,CTt,CTt_oth,OPT_FR_SOIL,OPT_STh,...
    zatm,disp_h,zom,zoh,zom_under,disp_h_H,zom_H,disp_h_L,zom_L,Ws,In_Litter,alp_litter,Lpho,Vavail,Vavail_plant_H,Vavail_plant_L,WAT_avail,ICEtm1,OPT_SoilTemp)
%%%%%%%%%%%%%%%%%%%%%
Ts_H=Ts(1); Ts_L=Ts(2);
%%%%
if sum(Ccrown)>0
    [ra]=Aerodynamic_Resistence(Ta,Ts_H,Pre,zatm,disp_h,zom,zoh,Ws,ea);
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    [rap_H,rap_L,rb_H,rb_L]=Undercanopy_Leaf_Resistence2(Ws,Ta,Ts_H,Ccrown,hc_H,hc_L,...
        (LAI_H+SAI_H),(LAI_L+SAI_L),d_leaf_H,d_leaf_L,...
        zatm,disp_h,zom,zom_under,SnoDep,disp_h_H,zom_H,disp_h_L,zom_L);
else
    [ra]=Aerodynamic_Resistence(Ta,Ts_L,Pre,zatm,disp_h,zom,zoh,Ws,ea);
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    [rap_H,rap_L,rb_H,rb_L]=Undercanopy_Leaf_Resistence2(Ws,Ta,Ts_L,Ccrown,hc_H,hc_L,...
        (LAI_H+SAI_H),(LAI_L+SAI_L),d_leaf_H,d_leaf_L,...
        zatm,disp_h,zom,zom_under,SnoDep,disp_h_H,zom_H,disp_h_L,zom_L);
end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%% Net Radiation
[Rnet_H,Rnet_L]=Net_Radiation_Manager_2Temp(Ts_H,Ts_L,Latm,SvF,...
    Csno,Crock,Curb,Cwat,Cbare,Cice,Ccrown,...
    hc_L,SnoDep,ydepth,ICE_D,Cdeb,LAI_H,LAI_L,SAI_H,SAI_L,...
    RabsbSun_vegH,RabsbShd_vegH,Rabsb_soiH,...
    RabsbSun_vegL,RabsbShd_vegL,Rabsb_soiL,FsunH,FshdH,...
    FsunL,FshdL,Rabsb_sno,Rabsb_bare,Rabsb_urb,Rabsb_wat,Rabsb_rock,Rabsb_ice,Rabsb_deb,...
    e_sno,e_gr,e_sur,Cicew,Csnow);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%% Ground Heat Flux still using a single column
if OPT_SoilTemp==1
    %%% Soil Heat Flux
    %[G]=Soil_Heat_Profile_New(Ts_L,dt,Tdptm1,ms,dz,Zs,Pre,rsd,lan_dry,lan_s,cv_s,SPAR,L,Pe,O33,alpVG,nVG,...
    %    Phy,s_SVG,bVG,Osat,Ohy,Oicetm1,Otm1,NaN,OPT_FR_SOIL,OPT_STh);

    [G]=Soil_Heat(dt,Ts_L,Tstm1_L,Tdamptm1,CTt);
else
    [G]=Soil_Heat(dt,Ts_L,Tstm1_L,Tdamptm1,CTt);
end
%%%%%%%%%%%%%
if Csno == 1 || Cice == 1 || Cdeb == 1 %% it should not happen but just in case 
    G_H=G; G_L=0;
else
    G_L=G; G_H=0;
end
%%% Heat Fluxes
[H_H,H_L,QE_H,QE_L,Qv_H,Qv_L]=Heat_fluxes_2Temp(dt,...
    Ta,Ts_H,Ts_L,ea,Pre,Csno,Crock,Curb,Cwat,Cbare,Cice,Cicew,Csnow,CLitter,Cdeb,...
    dw_L,dw_H,dw_SNO,Ccrown,FsunH,FshdH,...
    FsunL,FshdL,LAI_H,LAI_L,SAI_H,SAI_L,...
    In_H,In_L,In_urb,In_rock,SWE,In_SWE,...
    Pr_liq,Pr_sno,ra,rs_sunH,rs_sunL,rs_shdH,rs_shdL,rb_H,rb_L,rap_H,rap_L,r_litter,...
    r_soil,b_soil,alp_soil,Vavail,Vavail_plant_H,Vavail_plant_L,WAT_avail,ICEtm1,In_Litter,alp_litter);
%%%%%%% Energy Balance
DQ = [ Rnet_H-H_H-QE_H-G_H+Qv_H-Lpho;
Rnet_L-H_L-QE_L-G_L+Qv_L]; 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
return